version: 1
groups:
  - annotation: ckanext-auth
    options:
      - key: ckanext.auth.2fa_enabled
        default: true
        editable: true
        type: bool
        description: Enable two-factor authentication for users

      - key: ckanext.auth.2fa_method
        default: email
        editable: true
        description: The method to use for two-factor authentication. Options are email or authenticator.

      - key: ckanext.auth.2fa_email_interval
        default: 600
        editable: true
        type: int
        description: TTL for the authentication code sent via email in seconds. Default is 10 minutes.

      - key: ckanext.auth.2fa_login_timeout
        default: 900
        editable: true
        type: int
        description: Login timeout in seconds after N failed attempted. Default is 15 minutes.

      - key: ckanext.auth.2fa_login_max_attempts
        default: 10
        editable: true
        type: int
        description: Number of failed login attempts before the login timeout is triggered.
